#!/bin/bash
# shellcheck source-path=scripts/colorscheme

THEME_FILE="$1" # theme file containing colors
ACCENT="$2" # accent color from theme file

# shellcheck source=../colors/debug
source "$THEME_FILE"
# shellcheck source=../../.env
source "$HOME/dotfiles/.env"

CHOOSE_COLORS_FILE="$HOME/.config/choose/colors"
CHOOSE_FONT_FILE="$HOME/.config/choose/font"

# create choose config if it doesn't exist
if [[ ! -d "$HOME/.config/choose" ]]; then
  mkdir -p "$HOME/.config/choose"
fi

# choose: set colors file
echo "COLORSCHEME: setting choose colors"
cat << EOF > "$CHOOSE_COLORS_FILE"
ACCENT=$ACCENT
EOF

echo "COLORSCHEME: setting choose font"
cat << EOF > "$CHOOSE_FONT_FILE"
FONT="$CHOOSE_FONT"
EOF
