#!/bin/bash
# shellcheck source-path=scripts/colorscheme

THEME_FILE="$1" # theme file containing colors
ACCENT="$2" # accent color from theme file

# shellcheck source=../colors/debug
source "$THEME_FILE"
# shellcheck source=../../.env
source "$HOME/dotfiles/.env" # for $DUNST_FONT

DUNST_COLORS_FILE="$HOME/.config/dunst/dunstrc.d/colors.conf"
DUNST_FONT_FILE="$HOME/.config/dunst/dunstrc.d/font.conf"

# dunst: set colors
DUNST_CONFIG_DIR=$(dirname "$DUNST_COLORS_FILE")
if [[ ! -d $DUNST_CONFIG_DIR ]]; then mkdir -p "$DUNST_CONFIG_DIR"; fi

echo "COLORSCHEME: setting dunst colors"
cat << EOF > "$DUNST_COLORS_FILE"
[global]
    highlight = "$ACCENT"
    frame_color = "$ACCENT"

[urgency_low]
    background = "$BLACK"
    foreground = "$WHITE"

[urgency_normal]
    background = "$BLACK"
    foreground = "$WHITE"

[urgency_critical]
    background = "$BRIGHT_RED"
    foreground = "$WHITE"
EOF

echo "COLORSCHEME: setting dunst font"
cat << EOF > "$DUNST_FONT_FILE"
[global]
    font = $DUNST_FONT
EOF

# reload dunst
echo "COLORSCHEME: reloading dunst"
pkill dunst && dunst 1>/dev/null &
