#!/bin/bash
# shellcheck source-path=scripts/colorscheme

THEME_FILE="$1" # theme file containing colors
ACCENT="$2" # accent color from theme file
OPACITY="$3"

# shellcheck source=../colors/debug
source "$THEME_FILE"
# shellcheck source=../../.env
source "$HOME/dotfiles/.env" # for $KITTY_FONT_X

KITTY_COLORS_FILE="$HOME/.config/kitty/colors.conf"
KITTY_FONT_FILE="$HOME/.config/kitty/font.conf"

# kitty: set colors file
echo "COLORSCHEME: setting kitty colors"
# NOTE: remember to include $KITTY_COLORS_FILE in kitty config file
cat << EOF > "$KITTY_COLORS_FILE"
foreground $WHITE
background $BLACK
color0     $BLACK
color8     $GREY1
color1     $BRIGHT_RED
color9     $NEUTRAL_RED
color2     $BRIGHT_GREEN
color10    $NEUTRAL_GREEN
color3     $BRIGHT_YELLOW
color11    $NEUTRAL_YELLOW
color4     $BRIGHT_BLUE
color12    $NEUTRAL_BLUE
color5     $BRIGHT_PURPLE
color13    $NEUTRAL_PURPLE
color6     $BRIGHT_AQUA
color14    $NEUTRAL_AQUA
color7     $GREY3
color15    $WHITE

url_color  $ACCENT
active_border_color $ACCENT
inactive_border_color $ACCENT

selection_foreground $BLACK
selection_background $WHITE
cursor $WHITE
cursor_text_color $BLACK

background_opacity $OPACITY
dim_opacity 1.0

tab_title_template "{fmt.bg.default} {fmt.bg._${GREY0:1}}{fmt.fg._${BRIGHT_YELLOW:1}} {activity_symbol}{index} {fmt.bg._${GREY1:1}}{fmt.fg._${GREY5:1}} {tab.active_oldest_wd.split('/')[-1]} "
active_tab_title_template "{fmt.bg.default} {fmt.bg._${BRIGHT_YELLOW:1}}{fmt.fg._${BLACK:1}} {activity_symbol}{index} {fmt.bg._${NEUTRAL_YELLOW:1}}{fmt.fg._${BLACK:1}} {tab.active_oldest_wd.split('/')[-1]} "
EOF

echo "COLORSCHEME: setting kitty font"
# NOTE: remember to include $KITTY_FONT_FILE in kitty config file
cat << EOF > "$KITTY_FONT_FILE"
font_family      $KITTY_FONT_1
italic_font      $KITTY_FONT_2
bold_font        $KITTY_FONT_3
bold_italic_font $KITTY_FONT_4

font_size $KITTY_FONT_SIZE
EOF

# reload kitty
echo "COLORSCHEME: reloading kitty"
killall -SIGUSR1 kitty
