#!/bin/sh

THEME_FILE="$1" # theme file containing colors
ACCENT="$2" # accent color from theme file
OPACITY="$3"
BLACK_TR="$4"

source $THEME_FILE
source $HOME/dotfiles/.env

# on MacOS, turn dark mode on/off
echo "COLORSCHEME: setting MacOS theme to $MODE mode"
if [ $MODE = "light" ]; then
  osascript -e 'tell app "System Events" to tell appearance preferences to set dark mode to false'
else
  osascript -e 'tell app "System Events" to tell appearance preferences to set dark mode to true'
fi
