#!/bin/sh

THEME_FILE="$1" # theme file containing colors

source $THEME_FILE

NVIM_COLORS_FILE="$HOME/.config/nvim/lua/config/colors.lua"

# nvim: set colors file
echo "COLORSCHEME: setting nvim colors"
cat << EOF > $NVIM_COLORS_FILE
return {
  theme          = "$NAME",
  mode           = "$MODE",
  black          = "$BLACK",
  grey0          = "$GREY0",
  grey1          = "$GREY1",
  grey2          = "$GREY2",
  grey3          = "$GREY3",
  grey4          = "$GREY4",
  grey5          = "$GREY5",
  white          = "$WHITE",
  bright_red     = "$BRIGHT_RED",
  neutral_red    = "$NEUTRAL_RED",
  faded_red      = "$FADED_RED",
  bright_green   = "$BRIGHT_GREEN",
  neutral_green  = "$NEUTRAL_GREEN",
  faded_green    = "$FADED_GREEN",
  bright_yellow  = "$BRIGHT_YELLOW",
  neutral_yellow = "$NEUTRAL_YELLOW",
  faded_yellow   = "$FADED_YELLOW",
  bright_blue    = "$BRIGHT_BLUE",
  neutral_blue   = "$NEUTRAL_BLUE",
  faded_blue     = "$FADED_BLUE",
  bright_purple  = "$BRIGHT_PURPLE",
  neutral_purple = "$NEUTRAL_PURPLE",
  faded_purple   = "$FADED_PURPLE",
  bright_aqua    = "$BRIGHT_AQUA",
  neutral_aqua   = "$NEUTRAL_AQUA",
  faded_aqua     = "$FADED_AQUA",
  bright_orange  = "$BRIGHT_ORANGE",
  neutral_orange = "$NEUTRAL_ORANGE",
  faded_orange   = "$FADED_ORANGE",
}
EOF

# reload neovim
echo "COLORSCHEME: reloading neovim"
NVIM_SERVER="/tmp/nvim-server.pipe"
if [ -e $NVIM_SERVER ]; then
  NVIM=$(which nvim)
  # call reload function in nvim
  # NOTE: this function needs to exist
  $NVIM --server $NVIM_SERVER --remote-send ":lua reload_config()<CR>" & 2> /dev/null
else
  notify "$APPNAME" \
    "nvim server pipe not found at $NVIM_SERVER. No neovim instance is probably running. Skipping neovim theme..."
fi
