#!/bin/sh

THEME_FILE="$1" # theme file containing colors
ACCENT="$2" # accent color from theme file
OPACITY="$3"
BLACK_TR="$4"

source $THEME_FILE
source $HOME/dotfiles/.env

QUTEBROWSER_COLORS_FILE="$HOME/.config/qutebrowser/colors.py"
QUTEBROWSER_FONT_FILE="$HOME/.config/qutebrowser/font.py"

# qutebrowser: set theme
echo "COLORSCHEME: setting qutebrowser colors"
cat << EOF > $QUTEBROWSER_COLORS_FILE
MODE           = "$MODE"
BLACK          = "$BLACK"
GREY0          = "$GREY0"
GREY1          = "$GREY1"
GREY2          = "$GREY2"
GREY3          = "$GREY3"
GREY4          = "$GREY4"
GREY5          = "$GREY5"
WHITE          = "$WHITE"
BRIGHT_RED     = "$BRIGHT_RED"
NEUTRAL_RED    = "$NEUTRAL_RED"
FADED_RED      = "$FADED_RED"
BRIGHT_GREEN   = "$BRIGHT_GREEN"
NEUTRAL_GREEN  = "$NEUTRAL_GREEN"
FADED_GREEN    = "$FADED_GREEN"
BRIGHT_YELLOW  = "$BRIGHT_YELLOW"
NEUTRAL_YELLOW = "$NEUTRAL_YELLOW"
FADED_YELLOW   = "$FADED_YELLOW"
BRIGHT_BLUE    = "$BRIGHT_BLUE"
NEUTRAL_BLUE   = "$NEUTRAL_BLUE"
FADED_BLUE     = "$FADED_BLUE"
BRIGHT_PURPLE  = "$BRIGHT_PURPLE"
NEUTRAL_PURPLE = "$NEUTRAL_PURPLE"
FADED_PURPLE   = "$FADED_PURPLE"
BRIGHT_AQUA    = "$BRIGHT_AQUA"
NEUTRAL_AQUA   = "$NEUTRAL_AQUA"
FADED_AQUA     = "$FADED_AQUA"
BRIGHT_ORANGE  = "$BRIGHT_ORANGE"
NEUTRAL_ORANGE = "$NEUTRAL_ORANGE"
FADED_ORANGE   = "$FADED_ORANGE"
EOF

echo "COLORSCHEME: setting qutebrowser font"
cat << EOF > $QUTEBROWSER_FONT_FILE
# fonts
FONT_SIZE = $QUTEBROWSER_FONT_SIZE
MONO_FONT = '$QUTEBROWSER_MONO_FONT'
REGULAR_FONT = '$QUTEBROWSER_REGULAR_FONT'
EOF

# reload qutebrowser
echo "COLORSCHEME: reloading qutebrowser"
qutebrowser ":restart"
