#!/bin/sh

THEME_FILE="$1" # theme file containing colors
ACCENT="$2" # accent color from theme file
OPACITY="$3"
BLACK_TR="$4"

source $THEME_FILE
source $HOME/dotfiles/.env

ROFI_COLORS_FILE="$HOME/.config/rofi/colors.rasi"
ROFI_FONT_FILE="$HOME/.config/rofi/font.rasi"

# rofi: set colors file
echo "COLORSCHEME: setting rofi colors"
cat << EOF > $ROFI_COLORS_FILE
* {
  al:       $BLACK;
  bg:       $GREY0;
  se:       $GREY0;
  fg:       $WHITE;
  ac:       $ACCENT;
  red:      $BRIGHT_RED;
  green:    $BRIGHT_GREEN;
  yellow:   $BRIGHT_YELLOW;
  blue:     $BRIGHT_BLUE;
  purple:   $BRIGHT_PURPLE;
  aqua:     $BRIGHT_AQUA;
}
EOF

echo "COLORSCHEME: setting rofi font"
cat << EOF > $ROFI_FONT_FILE
configuration {
  font: "$ROFI_FONT";
}
EOF
