#!/bin/bash
# shellcheck source-path=scripts/colorscheme

THEME_FILE="$1" # theme file containing colors
ACCENT="$2" # accent color from theme file
BLACK_TR="$4"

# shellcheck source=colors/debug
source "$THEME_FILE"
# shellcheck source=../../.env
source "$HOME/dotfiles/.env" # for $SKETCHYBAR_FONT

SKETCHYBAR_COLORS_FILE="$HOME/.config/sketchybar/colors"
SKETCHYBAR_FONT_FILE="$HOME/.config/sketchybar/font"

# sketchybar: set colors file
echo "COLORSCHEME: setting sketchybar colors"
cat << EOF > "$SKETCHYBAR_COLORS_FILE"
#!/bin/sh

BLACKTR="$BLACK_TR"
BLACK="$BLACK"
GREY0="$GREY0"
GREY1="$GREY1"
GREY2="$GREY2"
GREY3="$GREY3"
GREY4="$GREY4"
WHITE="$WHITE"
BLUE0="$NEUTRAL_BLUE"
BLUE1="$BRIGHT_BLUE"
RED0="$NEUTRAL_RED"
RED1="$BRIGHT_RED"
ORANGE0="$NEUTRAL_ORANGE"
ORANGE1="$BRIGHT_ORANGE"
YELLOW0="$NEUTRAL_YELLOW"
YELLOW1="$BRIGHT_YELLOW"
GREEN0="$NEUTRAL_GREEN"
GREEN1="$BRIGHT_GREEN"
PURPLE0="$NEUTRAL_PURPLE"
PURPLE1="$BRIGHT_PURPLE"
CYAN0="$NEUTRAL_AQUA"
CYAN1="$BRIGHT_AQUA"
ACCENT="$ACCENT"
EOF

echo "COLORSCHEME: setting sketchybar font"
cat << EOF > "$SKETCHYBAR_FONT_FILE"
FONT="$SKETCHYBAR_FONT"
EOF

# reload sketchybar
echo "COLORSCHEME: reloading sketchybar"
brew services restart sketchybar
