#!/bin/bash
# shellcheck source-path=scripts/colorscheme

THEME_FILE="$1" # theme file containing colors

# shellcheck source=colors/debug
source "$THEME_FILE"

TMUX_COLORS_FILE="$HOME/.config/tmux/colors.conf"

# tmux: set colors file
echo "COLORSCHEME: setting tmux colors"
cat << EOF > "$TMUX_COLORS_FILE"
setenv -g brightorange "$BRIGHT_ORANGE"
setenv -g neutralorange "$NEUTRAL_ORANGE"
setenv -g fadedorange "$FADED_ORANGE"
EOF

# reload tmux
echo "COLORSCHEME: reloading tmux"
tmux source-file ~/.config/tmux/tmux.conf

