#!/bin/sh

ACCENT="$1" # accent color from theme file

XBORDERS_CONFIG_BASE_FILE="$HOME/dotfiles/xborders/.config/xborders/xborders.json"
XBORDERS_CONFIG_FILE="$HOME/.config/xborders/xborders.json"

# xborders: set config file
echo "COLORSCHEME: setting xborders colors"
jq ".[\"border-rgba\"] = \"${ACCENT}ff\"" "$XBORDERS_CONFIG_BASE_FILE" \
  > "$XBORDERS_CONFIG_FILE"

# reload xborders
echo "COLORSCHEME: reloading xborders"
/usr/local/bin/reborder
