#!/bin/bash
# shellcheck source-path=scripts/colorscheme

THEME_FILE="$1" # theme file containing colors
ACCENT="$2" # accent color from theme file
BLACK_TR="$4"

# shellcheck source=../colors/debug
source "$THEME_FILE"

YABAI_COLORS_FILE="$HOME/.config/yabai/colors"

# yabai set colors file
echo "COLORSCHEME: setting yabai colors"
cat << EOF > "$YABAI_COLORS_FILE"
#!/bin/sh

BLACKTR="$BLACK_TR"
BLACK="$BLACK"
GREY0="$GREY0"
GREY1="$GREY1"
GREY2="$GREY2"
GREY3="$GREY3"
GREY4="$GREY4"
WHITE="$WHITE"
BLUE0="$NEUTRAL_BLUE"
BLUE1="$BRIGHT_BLUE"
RED0="$NEUTRAL_RED"
RED1="$BRIGHT_RED"
ORANGE0="$NEUTRAL_ORANGE"
ORANGE1="$BRIGHT_ORANGE"
YELLOW0="$NEUTRAL_YELLOW"
YELLOW1="$BRIGHT_YELLOW"
GREEN0="$NEUTRAL_GREEN"
GREEN1="$BRIGHT_GREEN"
PURPLE0="$NEUTRAL_PURPLE"
PURPLE1="$BRIGHT_PURPLE"
CYAN0="$NEUTRAL_AQUA"
CYAN1="$BRIGHT_AQUA"
ACCENT="$ACCENT"
EOF

# reload yabai
echo "COLORSCHEME: reloading yabai"
yabai --stop-service
yabai --start-service
