#!/bin/bash
# shellcheck source-path=scripts/colorscheme

THEME_FILE="$1" # theme file containing colors
ACCENT="$2" # accent color from theme file

# shellcheck source=colors/debug
source "$THEME_FILE"

ZATHURA_COLORS_FILE="$HOME/.config/zathura/zathurarc"

# yabai set colors file
echo "COLORSCHEME: setting zathura colors"
cat << EOF > "$ZATHURA_COLORS_FILE"
set window-title-basename "true"
set selection-clipboard "clipboard"

set recolor true
map <C-i> recolor

set notification-error-bg "$NEUTRAL_RED"
set notification-error-fg "$ACCENT"
set notification-warning-bg "$NEUTRAL_YELLOW"
set notification-warning-fg "$BLACK"
set notification-bg "$GREY5"
set notification-fg "$ACCENT"

set completion-bg "$GREY5"
set completion-fg "$GREY3"
set completion-group-bg "$GREY5"
set completion-group-fg "$GREY3"
set completion-highlight-bg "$BLACK"
set completion-highlight-fg "$ACCENT"

set index-bg "$GREY5"
set index-fg "$ACCENT"
set index-active-bg "$BLACK"
set index-active-fg "$ACCENT"

set inputbar-bg "$GREY5"
set inputbar-fg "$ACCENT"

set statusbar-bg "$GREY5"
set statusbar-fg "$ACCENT"

set highlight-color "$NEUTRAL_YELLOW"
set highlight-active-color "$NEUTRAL_GREEN"

set default-bg "$GREY5"
set default-fg "$ACCENT"

set render-loading true
set render-loading-fg "$GREY5"
set render-loading-bg "$ACCENT"

# Recolor mode settings
set recolor-lightcolor "$GREY5"
set recolor-darkcolor "$ACCENT"
EOF

