#!/bin/sh

if [ $# -eq 0 ]
then
  # present a list of all items
  ITEM=$(bw list items | jq -r '.[].name' | uniq | sed 's/.*/\L\0/' | rofi -dmenu -p item)
  # TODO: filter by specific fields
  # jq -r ".[0] | .name + \":\" + .id + \":\" + .login.uris[0].uri + \":\" + .revisionDate"
else
  # get item from arguments
  ITEM=$@
fi

# get username and password for all matching items
JSON=$(bw list items --search $ITEM | jq '[.[].login | { username, password }]')

# present a list of usernames
USERNAME=$(echo $JSON | jq -r '.[].username' | rofi -dmenu -p 🔎)

# check whether username exists
if [ "$USERNAME" = "" ]
then
  dunstify --appname="bitwarden script" --block --urgency=2 "Username could not be captured!" &
  exit
fi

# filter out password using username
PASSWORD=$(echo $JSON | jq -r "map(select(.username == \"$USERNAME\")) | .[0].password" )

# paste password to clipboard
echo $PASSWORD | xclip -r -selection clipboard

dunstify --appname="bitwarden script" "Password copied to clipboard for username: $USERNAME"
