#!/bin/sh

CONFIG_DIR="$HOME/.config"

choose_config () {
  find "$CONFIG_DIR"/* -maxdepth 0 -type d -printf "%f\n" | fzf
}

modify_config () {
  if [ $# -eq 0 ]
  then
    echo "[configctl] No program specified to modify_config"
    exit
  fi
  $EDITOR "$CONFIG_DIR/$1"
}

modify_config "$(choose_config)"
