#!/bin/sh

device=$(ponymix | grep -A1 -i "sink" | tail -n 1 | sed 's/^\s\+//')

case "$device" in
  "Tiger Lake-LP Smart Sound Technology Audio Controller Speaker + Headphones") echo "laptop-audio" ;;
  "Tiger Lake-LP Smart Sound Technology Audio Controller Speaker") echo "laptop-audio" ;;
  *) echo "$device" ;;
esac
