#!/bin/sh

PRIMARY="eDP-1"
PRIMARY_MODE="1920x1080"
SECONDARY="DP-2-1-8"
SECONDARY_MODE="2560x1440"

display_on() {
  xrandr --output $1 --primary --mode $2
}
display_off() {
  xrandr --output $1 --off
}
display_dim() {
  xrandr --output $1 --brightness 0
}
display_undim() {
  xrandr --output $1 --brightness 1
}

primary_only() {
  display_on $PRIMARY $PRIMARY_MODE && display_off $SECONDARY
}
secondary_only() {
  display_off $PRIMARY && display_on $SECONDARY $SECONDARY_MODE
}

case $1 in
  "primary") primary_only ;;
  "secondary") secondary_only ;;
  "dim-primary") display_dim $PRIMARY ;;
  "dim-secondary") display_dim $SECONDARY ;;
  "undim-primary") display_undim $PRIMARY ;;
  "undim-secondary") display_undim $SECONDARY ;;
  *) echo "Invalid Option. Please select either 'primary', 'secondary', 'dim-primary', 'dim-secondary', 'undim-primary' or 'undim-secondary'" ;;
esac
