#!/bin/sh

# Using the spotify web api: https://developer.spotify.com/documentation/web-api/reference/
SPOTIFY_AUTH_URL="https://accounts.spotify.com/api/token"
SPOTIFY_CLIENT_ID=""
SPOTIFY_CLIENT_SECRET=""
SPOTIFY_ENCODED_CREDS=$(printf '%s:%s' "$SPOTIFY_CLIENT_ID" "$SPOTIFY_CLIENT_SECRET" | base64)
SPOTIFY_API_URL="https://api.spotify.com"
SPOTIFY_REFRESH_TOKEN=""

# file to save current token and expiration time to
TOKEN_STORE=/tmp/spotify-mp3-tag

# to extract fields from response
RESPONSE_FIELD_TITLE='.name'
RESPONSE_FIELD_ARTIST='.artists[0].name'
RESPONSE_FIELD_ALBUM='.album.name'
RESPONSE_FIELD_YEAR='.album.release_date'
RESPONSE_FIELD_TRACKNUM='.track_number'
RESPONSE_FIELD_IMGURL='.album.images[0].url'

# function to refresh spotify access token
refresh_token () {
  AUTH_RESPONSE=$(curl \
    --silent \
    --header "Authorization: Basic $SPOTIFY_ENCODED_CREDS" \
    --header "Content-Type: application/x-www-form-urlencoded" \
    --data-urlencode "grant_type=refresh_token" \
    --data-urlencode "refresh_token=$SPOTIFY_REFRESH_TOKEN" \
    --request POST $SPOTIFY_AUTH_URL)

  # get relevant fields
  SPOTIFY_ACCESS_TOKEN=$(echo "$AUTH_RESPONSE" | jq '.access_token' | sed 's/\"//g')
  EXPIRY_SECONDS=$(echo "$AUTH_RESPONSE" | jq '.expires_in')

  # calculate expiration timestamp
  EXPIRATION_TIMESTAMP=$(date +"%s" | xargs echo "$EXPIRY_SECONDS + " | bc)
  # save expiry timestamp and access token in tmp
  echo "{ \"token\": \"$SPOTIFY_ACCESS_TOKEN\", \"expiration\": $EXPIRATION_TIMESTAMP }" > $TOKEN_STORE
}

main () {
  # handle input arguments
  if [ $# -eq 0 ]
  then
    echo "No track name specified"
    exit
  fi

  # sanitize input
  QUERY=$(echo "$1" | sed 's/ /+/g')

  # read stored expiry timestamp if exists
  if [ -e $TOKEN_STORE ]
  then
    # get current token and expiration timestamp
    SPOTIFY_ACCESS_TOKEN=$(cat $TOKEN_STORE | jq '.token' | sed 's/\"//g')
    EXPIRATION_TIMESTAMP=$(cat $TOKEN_STORE | jq '.expiration')
    CURRENT_TIMESTAMP=$(date +"%s")
    if [ "$EXPIRATION_TIMESTAMP" -lt "$CURRENT_TIMESTAMP" ]
    then
      refresh_token
    fi
  else
    #  TODO: refactor redundant code
    refresh_token
  fi

  # perform search for song details
  curl \
    --silent \
    --header "Authorization: Bearer $SPOTIFY_ACCESS_TOKEN" \
    --request GET "$SPOTIFY_API_URL/v1/search?q=$QUERY&type=track" \
  | jq "[.tracks.items[] | {
    title: $RESPONSE_FIELD_TITLE,
    artist: $RESPONSE_FIELD_ARTIST,
    album: $RESPONSE_FIELD_ALBUM,
    year: $RESPONSE_FIELD_YEAR,
    track: $RESPONSE_FIELD_TRACKNUM,
    img: $RESPONSE_FIELD_IMGURL
  }]"
}

main "$1"

