#!/bin/sh

volume_up() {
  ponymix increase 1
}

volume_down() {
  ponymix decrease 1
}

get_volume() {
  ponymix get-volume
}

show_notification() {
  dunstify -a " " -h string:x-canonical-private-synchronous:volume "Volume" -h int:value:"$1"
}

if [[ $1 == "+" || $1 == "up" || $1 == "inc" ]]; then
  volume_up
  show_notification $(get_volume)
elif [[ $1 == "-" || $1 == "down" || $1 == "dec" ]]; then
  VAL=$(volume_down)
  show_notification $(get_volume)
else
  echo "invalid argument"
fi
