#!/bin/sh

COLORS="$HOME/.config/sketchybar/colors"
source "$COLORS"

OUT=$(pmset -g batt)
IS_CHARGING=$(pmset -g batt | grep -E -q 'discharging' && echo 'FALSE' || echo 'TRUE')
BATT_PERCENT=$(echo $OUT | grep -E -o '\d+%' | cut -d '%' -f 1)
ICON=""
ICON_COLOR="${ACCENT:1}"

if [ $IS_CHARGING = "TRUE" ]; then
  ICON=""
  ICON_COLOR="${CYAN0:1}"
else
  case $BATT_PERCENT in
    100) ICON="" ;;
    9[0-9]) ICON="" ;;
    8[0-9]) ICON="" ;;
    7[0-9]) ICON="" ;;
    6[0-9]) ICON="" ;;
    5[0-9]) ICON="" ;;
    4[0-9]) ICON="" ;;
    3[0-9]) ICON="" ;;
    2[0-9]) ICON="" ;;
    1[0-9]) ICON="" ;;
    *) ICON=""
  esac
fi

sketchybar -m --set $NAME \
  label="$BATT_PERCENT%"     \
  icon="$ICON"              \
  icon.color="0xFF${ICON_COLOR}"
