#!/bin/bash

RESULT=$(
  jira sprint list \
    --state active \
    --table --plain --no-headers \
    --columns name,end \
    | grep -i "achievers"
)

# split on tabs
SPRINT=$(echo "$RESULT" | cut -d "	" -f 1 | grep -i "sprint \d\+" -o)
END=$(echo "$RESULT" | cut -d "	" -f 2)

if [[ "$SPRINT" == "" ]] || [[ "$END" == "" ]]; then
  sketchybar -m --set jira label="$RESULT"
  exit 1
fi

# get sprint end and current timestamps
CURR_TS=$(date +%s)
END_TS=$(date -j -f '%Y-%m-%d %H:%M:%S' "$END" +'%s')

# calculate number of days
DIFF=$(( ($END_TS - $CURR_TS) / (24 * 60 * 60)))
NOTIFY="$SPRINT ends in $DIFF day(s)"

sketchybar -m --set jira label="$NOTIFY"
