#!/bin/bash

IS_SHORT="$1"

# scripts dir
SCRIPTS="$HOME/.config/sketchybar/scripts"

CACHE="$HOME/.config/sketchybar/scripts/jira-curr-sprint"

# read cached result if it exists
RESULT=$(cat "$CACHE" 2> /dev/null)

# split on tabs
SPRINT=$(echo "$RESULT" | cut -d "	" -f 1 | grep -i "sprint \d\+" -o)
END=$(echo "$RESULT" | cut -d "	" -f 2)

if [[ "$RESULT" == "" || "$END" == "" ]]; then
  sketchybar -m --set $NAME label="fetching..."
  # fetch from API
  export JIRA_API_TOKEN="$(cat $HOME/.secrets/JIRA_API_TOKEN)"
  RESULT=$(
    jira sprint list \
      --state active \
      --table --plain --no-headers \
      --columns name,end \
      | grep -i "achievers"
  )

  # save result as cache
  echo "$RESULT" > "$CACHE"

  # parse values again
  SPRINT=$(echo "$RESULT" | cut -d "	" -f 1 | grep -i "sprint \d\+" -o)
  END=$(echo "$RESULT" | cut -d "	" -f 2)
fi

NOTIFY=""
if [[ "$RESULT" == "" ]]; then
  NOTIFY="No active sprints"
elif [[ "$SPRINT" == "" ]] || [[ "$END" == "" ]]; then
  NOTIFY="ERROR"
else
  # get sprint end and current timestamps
  CURR_TS=$(date +%s)
  END_TS=$(date -j -f '%Y-%m-%d %H:%M:%S' "$END" +'%s')

  # calculate number of days
  DIFF=$(( ($END_TS - $CURR_TS) / (24 * 60 * 60) + 1))
  NOTIFY="$SPRINT ends in $DIFF day(s)"
fi

if [ "$IS_SHORT" = "0" ]; then
  sketchybar -m --set $NAME label="$NOTIFY" click_script="rm -rf \"$CACHE\" && $SCRIPTS/jira"
fi
