#!/bin/sh

# this script will be called by sketchybar with the media_changed event
# subscribed providing media info in $INFO
APP="$(echo "$INFO" | jq -r '.app')"
META="$(echo "$INFO" | jq -r '.artist + " - " + .title')"

osascript -e "display notification \"$META\" with title \"$APP\""

sketchybar -m --set spotify label="$META"
