#!/bin/sh

IS_SHORT=$1
if [ $IS_SHORT ]; then
  CUTOFF=30
else
  CUTOFF=80
fi

if [[ $INFO = "iTerm2" ]]; then
  TITLE="Terminal"
elif [[ $INFO = "kitty" ]]; then
  TITLE="Terminal"
else
  if [[ ${#INFO} -gt $CUTOFF ]]; then
    TITLE="$(echo "$INFO" | head -c $CUTOFF)…"
  else
    TITLE=$INFO
  fi
fi

sketchybar -m --set title label="$TITLE"
