#!/bin/sh

IS_SHORT=$1
if [ $IS_SHORT ]; then
  CUTOFF=30
else
  CUTOFF=80
fi

WINDOW=$(/opt/homebrew/bin/yabai -m query --windows --window)
WINDOW_APP=$(echo $WINDOW | jq -r ".app")
WINDOW_TITLE=$(echo $WINDOW | jq -r ".title")

if [[ $WINDOW_APP = "iTerm2" ]]; then
  TITLE="Terminal"
elif [[ $WINDOW_TITLE = "" ]]; then
  TITLE=$WINDOW_APP
else
  if [[ ${#WINDOW_TITLE} -gt $CUTOFF ]]; then
    TITLE="$(echo "$WINDOW_TITLE" | head -c $CUTOFF)…"
  else
    TITLE=$WINDOW_TITLE
  fi
fi

sketchybar -m --set title label="$TITLE"
