#!/bin/sh

WINDOW=$(/opt/homebrew/bin/yabai -m query --windows --window)
WINDOW_APP=$(echo $WINDOW | jq -r ".app")
WINDOW_TITLE=$(echo $WINDOW | jq -r ".title")

if [[ $WINDOW_APP = "iTerm2" ]]; then
  TITLE="Terminal"
elif [[ $WINDOW_TITLE = "" ]]; then
  TITLE=$WINDOW_APP
else
  if [[ ${#WINDOW_TITLE} -gt 80 ]]; then
    TITLE="$(echo "$WINDOW_TITLE" | cut -c 1-50)…"
  else
    TITLE=$WINDOW_TITLE
  fi
fi

sketchybar -m --set title label="$TITLE"
