#!/bin/sh

IS_SHORT="$1"
if [ "$IS_SHORT" = "1" ]; then
  ICON=" "
else
  ICON=" VPN"
fi

source "$HOME/.config/sketchybar/colors"

STATE=$(/opt/cisco/anyconnect/bin/vpn state | grep -i "state: connected" | wc -l)

if [ $STATE -eq 0 ]
then
  # CONNECTED="NO"
  COLOR="0xFF${RED0:1}"
else
  # CONNECTED="YES"
  COLOR="0xFF${GREEN0:1}"
fi

sketchybar -m --set $NAME icon.color="$COLOR" icon="$ICON"
