#!/bin/sh

IS_SHORT="$1"

WEATHER_ICON=$(curl --silent "wttr.in/?format=%c")
if [[ "$WEATHER_ICON" =~ "Unknown location" ]]; then
  sketchybar -m --set "$NAME" label="Error with wttr.in"
  exit
fi

if [ "$IS_SHORT" = "1" ]; then
  CURR_TEMP=$(curl --silent "wttr.in/?format=j1" | jq -r '.current_condition[0] | .temp_F+"°F"')
  WEATHER="$CURR_TEMP"
else
  MINMAX=$(curl --silent "wttr.in/?format=j1" | jq -r '.weather[0] | .maxtempF+"°F/"+.mintempF+"°F"')
  WEATHER="$MINMAX $WEATHER_ICON"
fi

sketchybar -m --set "$NAME" label="$WEATHER"
