#!/bin/sh

CURRENT_WIFI="$(/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I)"
SSID="$(echo "$CURRENT_WIFI" | grep -o "SSID: .*" | sed 's/^SSID: //')"

if [ "$SSID" = "" ]; then
  if [ "$1" = "1" ]; then
    LABEL=""
    ICON="睊 "
  else
    LABEL="no-internet"
    ICON="睊 "
  fi
else
  if [ "$1" = "1" ]; then
    LABEL=""
    ICON=" "
  else
    LABEL="$SSID"
    ICON=" "
  fi
fi

sketchybar --set $NAME label="$LABEL" icon="$ICON"
