#!/bin/sh

CURRENT_WIFI="$(/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I)"
SSID="$(echo "$CURRENT_WIFI" | grep -o "SSID: .*" | sed 's/^SSID: //')"

if [ "$SSID" = "" ]; then
  if [ "$1" = "1" ]; then
    sketchybar --set wlan label="" icon="睊 "
  else
    sketchybar --set wlan label="no-internet" icon="睊 "
  fi
else
  if [ "$1" = "1" ]; then
    sketchybar --set wlan label="" icon=" "
  else
    sketchybar --set wlan label="$SSID" icon=" "
  fi
fi
