#!/bin/sh

LAPTOP="eDP-1"
ULTRAWIDE="DP-1"
PORTRAIT="DP-3-1-8"

# turn_off() {
  
# }

ultrawide_only() {
  xrandr --output $ULTRAWIDE --primary --mode 2560x1440 --pos 0x240 --rotate normal
}

portrait_only() {
  xrandr --output $PORTRAIT --mode 1920x1080 --pos 2560x0 --rotate right
}

internal_only() {
  xrandr --output $LAPTOP --mode 1920x1200 --pos 0x0 --rotate normal
}

external() {
  turn_off
  internal_only
  ultrawide_only
  portrait_only
}

case $1 in
  "laptop") internal_only ;;
  "external") external ;;
  *) echo "Invalid Option. Please select either 'laptop' or 'external'" ;;
esac
