#!/bin/sh

INTERNAL="eDP-1"
ULTRAWIDE="DP-3-1-8"
PORTRAIT=""

internal_on() {
  xrandr --output $INTERNAL --mode 1920x1200
}
internal_off() {
  xrandr --output $INTERNAL --off
}

ultrawide_on() {
  xrandr --output $ULTRAWIDE --mode 2560x1440
}
ultrawide_off() {
  xrandr --output $ULTRAWIDE --off
}

portrait_on() {
  xrandr --output $PORTRAIT --mode 1920x1080
}
portrait_on() {
  xrandr --output $PORTRAIT --off
}

internal_only() {
  internal_on && ultrawide_off
}

ultrawide_only() {
  ultrawide_on && internal_off
}

# portrait_only() {
#   xrandr --output $PORTRAIT --mode 1920x1080 --pos 2560x0 --rotate right
# }

case $1 in
  "internal") internal_only ;;
  "external") ultrawide_only ;;
  *) echo "Invalid Option. Please select either 'internal' or 'external'" ;;
esac
