#!/bin/sh

DEVICES=$(bluetoothctl devices)
SELECTION=$(echo "$DEVICES" | awk -F' ' '{print $3}' | fzf --prompt="connect to which device? ")
ID=$(echo "$DEVICES" | grep "$SELECTION" | awk -F' ' '{print $2}')
echo "connecting to $SELECTION..."
bluetoothctl connect "$ID"
