#!/usr/bin/env sh

limelight -m config width 2
limelight -m config radius 10
limelight -m config placement exterior
# limelight -m config active_color 0xFF8EC07C
limelight -m config active_color 0xFF689D6A
# limelight -m config active_color 0xFF10ff91
limelight -m config normal_color 0x00FFFFFF

echo "limelight configuration loaded.."
