#!/bin/sh

# Colors  (printf)
c_red="\033[1;31m"
c_green="\033[1;32m"
c_yellow="\033[1;33m"
c_blue="\033[1;34m"
c_magenta="\033[1;35m"
c_cyan="\033[1;36m"
c_reset="\033[0m"

query="$(echo $1 | sed 's/ /+/g; s/&/%26/g; s/?/%3F/g')"
link="https://www.youtube.com/results?search_query=$query"
useragent=${useragent-'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.152 Safari/537.36'}
sp=""

# scrape youtube search result html
yt_html="$(
curl "$link" -s \
  -G --data-urlencode "search_query=$query" \
  -G --data-urlencode "sp=$sp" \
  -H 'authority: www.youtube.com' \
  -H "user-agent: $useragent" \
  -H 'accept-language: en-US,en;q=0.9' \
  --compressed
)"

# extract json from html
yt_json=$(echo "$yt_html" |\
  sed -n '/var *ytInitialData/,$p' |\
  tr -d '\n' |\
  sed -E ' s_^.*var ytInitialData ?=__ ; s_;</script>.*__ ;')

# parse json and get metadata
videos_json=$(printf "%s" "$yt_json" |\
  jq '[ .contents | .. | .videoRenderer? | select(. != null) |
  {
    title: .title.runs[0].text,
    channel: .longBylineText.runs[0].text,
    duration:.lengthText.simpleText,
    views: .shortViewCountText.simpleText,
    date: .publishedTimeText.simpleText,
    videoID: .videoId,
    thumbs: .thumbnail.thumbnails[0].url
  }
]')

# output
# echo -e "$c_blue$videos_json" | jq -r '.[].title'
echo -e "$c_blue$videos_json" | jq -r '[].title'

# color output
# echo -e "${c_blue}Channel ${c_green}hello"
