#!/usr/bin/env sh

# for this to work you must configure sudo such that
# it will be able to run the command without password
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m space 1 --label 1
yabai -m space 2 --label 2
yabai -m space 3 --label 3
yabai -m space 4 --label 4
yabai -m space 5 --label 5
yabai -m space 6 --label 6
yabai -m space 9 --label 9

# float system preferences. Most of these just diable Yabai form resizing them.
yabai -m rule --add app="^System Preferences$"      sticky=on layer=above manage=off
yabai -m rule --add app="^Finder$"                  sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$"            sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$"      sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$"        sticky=on layer=above manage=off
yabai -m rule --add app="^Simulator$"               sticky=on layer=above manage=off
yabai -m rule --add app="^Path Finder$"             manage=off
yabai -m rule --add app="^Time Out$"                manage=off
yabai -m rule --add app="^Private Internet Access$" manage=off
yabai -m rule --add app="^choose$"                  sticky=on layer=above manage=off

yabai -m config auto_padding on
yabai -m config auto_padding_min_aspect 3.00
yabai -m config auto_padding_width 80
yabai -m config auto_padding_height 1200

source ~/.config/yabai/colors

yabai -m config                               \
  mouse_follows_focus          off            \
  focus_follows_mouse          autofocus      \
  window_origin_display        default        \
  window_placement             second_child   \
  window_topmost               off            \
  window_shadow                on             \
  window_animation_duration    0.0            \
  window_opacity_duration      0.0            \
  active_window_opacity        1.0            \
  normal_window_opacity        0.90           \
  window_opacity               off            \
  insert_feedback_color        0xff${RED0:1}  \
  active_window_border_color   0xff${ACCENT:1}\
  normal_window_border_color   0xff${GREY0:1} \
  window_border_width          3              \
  window_border_radius         12             \
  window_border_blur           off            \
  window_border_hidpi          on             \
  window_border                on             \
  split_ratio                  0.50           \
  split_type                   auto           \
  auto_balance                 off            \
  top_padding                  40             \
  bottom_padding               20             \
  left_padding                 20             \
  right_padding                20             \
  window_gap                   20             \
  layout                       bsp            \
  mouse_modifier               cmd            \
  mouse_action1                move           \
  mouse_action2                resize         \
  mouse_drop_action            swap

echo "yabai configuration loaded.."

