#!/bin/sh

hex2decimal () {
  # convert to uppercase for bc
  TEMP=$(echo $1 | tr '[:lower:]' '[:upper:]')
  # get decimal value from hexadecimal
  TEMP=$(echo "ibase=16; $TEMP" | bc)
  # get ratio out of 255
  TEMP=$(echo "scale=10; $TEMP / 255" | bc | awk '{printf "%f", $0}')
  echo $TEMP
}

hex2rgb () {
  R=$(hex2decimal ${1:1:2})
  G=$(hex2decimal ${1:3:2})
  B=$(hex2decimal ${1:5:2})
  echo "$R:$G:$B"
}
