#!/bin/sh

APPNAME="colorscheme script"

hex2decimal () {
  # convert to uppercase for bc
  TEMP=$(echo $1 | tr '[:lower:]' '[:upper:]')
  # get decimal value from hexadecimal
  TEMP=$(echo "ibase=16; $TEMP" | bc)
  # get ratio out of 255
  TEMP=$(echo "scale=10; $TEMP / 255" | bc | awk '{printf "%f", $0}')
  echo $TEMP
}

hex2rgb () {
  R=$(hex2decimal ${1:1:2})
  G=$(hex2decimal ${1:3:2})
  B=$(hex2decimal ${1:5:2})
  echo "$R:$G:$B"
}

rgb2hex () {
  if [[ ! $# -eq 3 ]]; then
    echo "need 3 args for red, green and blue!"
  fi
  R=$(printf '%02x' $1)
  G=$(printf '%02x' $2)
  B=$(printf '%02x' $3)

  echo "#$R$G$B"
}

notify () {
  UNAME=$(uname -s)
  if [ $UNAME = "Darwin" ]; then
    osascript -e "display notification \"$2\" with title \"$1\""
  else
    notify-send -a "$1" "$2"
  fi
}

quit_on_error () {
  # if there was an error in the last command, quit
  if [ $? != 0 ]; then
    # if argument with message was passed in, send notification
    if [ $# != 0 ]; then
      notify "$APPNAME" "$1"
    fi
    exit 1
  fi
}

quit_on_file_dne () {
  # if no argument with filepath was passed in, quit
  if [ $# = 0 ]; then
    notify "$APPNAME" "\`quit_on_file_dne\` called without argument! Exiting..."
    exit 1
  fi
  if [ ! -e "$1" ]; then
    notify "$APPNAME" "$1 was not found. Exiting..."
    exit 1
  fi
}
